-- Convierte columnas NUMERIC a DOUBLE PRECISION para compatibilidad con f64 en SQLx
ALTER TABLE conductor_types
    ALTER COLUMN r_ohm_km    TYPE DOUBLE PRECISION USING r_ohm_km::DOUBLE PRECISION,
    ALTER COLUMN x_ohm_km    TYPE DOUBLE PRECISION USING x_ohm_km::DOUBLE PRECISION,
    ALTER COLUMN rn_ohm_km   TYPE DOUBLE PRECISION USING rn_ohm_km::DOUBLE PRECISION,
    ALTER COLUMN xn_ohm_km   TYPE DOUBLE PRECISION USING xn_ohm_km::DOUBLE PRECISION,
    ALTER COLUMN rpn_ohm_km  TYPE DOUBLE PRECISION USING rpn_ohm_km::DOUBLE PRECISION,
    ALTER COLUMN xpn_ohm_km  TYPE DOUBLE PRECISION USING xpn_ohm_km::DOUBLE PRECISION,
    ALTER COLUMN b_us_km     TYPE DOUBLE PRECISION USING b_us_km::DOUBLE PRECISION,
    ALTER COLUMN b0_us_km    TYPE DOUBLE PRECISION USING b0_us_km::DOUBLE PRECISION,
    ALTER COLUMN bn_us_km    TYPE DOUBLE PRECISION USING bn_us_km::DOUBLE PRECISION,
    ALTER COLUMN bpn_us_km   TYPE DOUBLE PRECISION USING bpn_us_km::DOUBLE PRECISION,
    ALTER COLUMN i_ground_ka TYPE DOUBLE PRECISION USING i_ground_ka::DOUBLE PRECISION,
    ALTER COLUMN i_air_ka    TYPE DOUBLE PRECISION USING i_air_ka::DOUBLE PRECISION;
